export const ADD_ONE_PRODUCT = 'ADD_ONE_PRODUCT';
export const CLEAR_CART = 'CLEAR_CART';
export const DELETE_ONE_ITEM = 'DELETE_ONE_ITEM';
export const INCREASE_PRODUCT_COUNT = 'INCREASE_PRODUCT_COUNT';
export const DECREASE_PRODUCT_COUNT = 'DECREASE_PRODUCT_COUNT';

export const ADD_DEFAULT_VARIANTS = 'ADD_DEFAULT_VARIANTS';
export const DELETE_DEFAULT_VARIANTS = 'DELETE_DEFAULT_VARIANTS';
export const EDIT_DEFAULT_VARIANTS = 'EDIT_DEFAULT_VARIANTS';

export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGRIES_ERR = 'CATEGRIES_ERR';

export const ADD_SELECTDATA = 'ADD_SELECTDATA';
export const DELETE_SELECTDATA = 'DELETE_SELECTDATA';

export const GET_BRANDS = 'GET_BRANDS';
export const BRANDS_LOADING = 'BRANDS_LOADING';
export const BRANDS_ERR = 'BRANDS_ERR';

export const GET_FEATURED_PRODUCTS = 'GET_FEATURED_PRODUCTS';
export const FEATURED_PRODUCTS_LOADING = 'FEATURED_PRODUCTS_LOADING';
export const FEATURED_PRODUCTS_ERR = 'FEATURED_PRODUCTS_ERR';

export const GET_DISCOUNT_PRODUCT = 'GET_DISCOUNT_PRODUCT';
export const DISCOUNT_PRODUCT_LOADING = 'DISCOUNT_PRODUCT_LOADING';
export const DISCOUNT_PRODUCT_ERR = 'DISCOUNT_PRODUCT_ERR';

export const GET_COLLECTION_DATA = 'GET_COLLECTION_DATA';
export const COLLECTION_DATA_LOADING = 'COLLECTION_DATA_LOADING';
export const COLLECTION_DATA_ERR = 'COLLECTION_DATA_ERR';

export const ADD_SEARCH_QUERY = 'ADD_SEARCH_QUERY';
export const DELETE_SEARCH_QUERY = 'DELETE_SEARCH_QUERY';

export const ADD_ONE_FAVOURITE = 'ADD_ONE_FAVOURITE';
export const REMOVE_ONE_FAVOURITE = 'REMOVE_ONE_FAVOURITE';
export const REMOVE_ALL_FAVOURITES = 'REMOVE_ALL_FAVOURITES';

//  ABANDONED ID
export const ADD_ABANDONED_ID = 'ADD_ABANDONED_ID';
export const DELETE_ABANDONED_ID = 'DELETE_ABANDONED_ID';
export const ABANDONED_ID_LOADING = 'ABANDONED_ID_LOADING';
export const ABANDONED_ID_ERR = 'ABANDONED_ID_ERR';


// SUBSCRIPTION DATA
export const ADD_SUBSCRIPTION_ID = 'ADD_SUBSCRIPTION_ID';
export const DELETE_SUBSCRIPTION_ID = 'DELETE_SUBSCRIPTION_ID';
export const SUBSCRIPTION_ID_LOADING = 'SUBSCRIPTION_ID_LOADING';
export const SUBSCRIPTION_ID_ERR = 'SUBSCRIPTION_ID_ERR';
export const ADD_SUBSCRIPTION_FAQ_ID = 'ADD_SUBSCRIPTION_FAQ_ID'
export const DELETE_SUBSCRIPTION_FAQ_ID = 'DELETE_SUBSCRIPTION_FAQ_ID'