export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_ERR = 'LOGIN_ERR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const SKIPPED_LOGIN = 'SKIPPED_LOGIN';
export const ADDRESS_SELECTED = 'ADDRESS_SELECTED';

export const START_SELF_PICKUP = 'START_SELF_PICKUP';
export const START_HOME_DELIVERY = 'START_HOME_DELIVERY';
export const RE_LOGIN = 'RE_LOGIN';
export const LOGING_FROM_CART = 'LOGING_FROM_CART';
export const LOGING_FROM_START = 'LOGING_FROM_START';

export const FULL_TIME_DELIVERY = 'FULL_TIME_DELIVERY';
export const NORMAL_DELIVERY = 'NORMAL_DELIVERY';
export const GET_USER_ADDRESSES = 'GET_USER_ADDRESSES';
export const USER_ADDRESSES_LOADING = 'USER_ADDRESSES_LOADING';
export const USER_ADDRESSES_FAILED = 'USER_ADDRESSES_FAILED';
export const ADD_SELECTED_ADDRESS = 'ADD_SELECTED_ADDRESS';

export const USERDATA_LOADING = 'USERDATA_LOADING';
export const USERDATA_ERR = 'USERDATA_ERR';
export const USERDATA_SUCCESS = 'USERDATA_SUCCESS';

export const ADD_NEAREST_SUPPLIER = 'ADD_NEAREST_SUPPLIER';
export const DELETE_NEAREST_SUPPLIER = 'DELETE_NEAREST_SUPPLIER';

export const REMOVE_SELECTED_ADDRESS_AND_SUPPLIER_WITH_MIN_DIST =
  'REMOVE_SELECTED_ADDRESS_AND_SUPPLIER_WITH_MIN_DIST';

export const VISITED_PROFILE_ONES = 'VISITED_PROFILE_ONES';

export const GET_REFFERAL_CODE = 'GET_REFFERAL_CODE';

export const GET_WALLET_DATA = 'GET_WALLET_DATA';
export const WALLET_DATA_LOADING = 'WALLET_DATA_LOADING';

export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const USER_ORDERS_LOADING = 'USER_ORDERS_LOADING';

export const ADDED_REDDERAL_CODE = 'ADDED_REDDERAL_CODE';

export const WALLET_TRANSACTIONS_LOADING = 'WALLET_TRANSACTIONS_LOADING';
export const GET_WALLET_TRANSACTIONS = 'GET_WALLET_TRANSACTIONS';

export const GET_SOCIETY_DATA = 'GET_SOCIETY_DATA';
export const SOCIETY_DATA_LOADING = 'SOCIETY_DATA_LOADING';

export const SAVE_COUPONCODE_RESPONSE = 'SAVE_COUPONCODE_RESPONSE';
export const DELETE_COUPON_RESPONSE = 'DELETE_COUPON_RESPONSE';

export const ADD_SUPPLIER_DATA = 'ADD_SUPPLIER_DATA';
export const DELETE_SUPPLIER_DATA = 'DELETE_SUPPLIER_DATA';
export const SUPPLIER_DATA_LOADING = 'SUPPLIER_DATA_LOADING';
export const SUPPLIER_DATA_ERR = 'SUPPLIER_DATA_ERR';


//PAYMENT GATEWAY
export const ADD_PAYMENT_GATEWAY = "ADD_PAYMENT_GATEWAY";
export const DELETE_PAYMENT_GATEWAY = "DELETE_PAYMENT_GATEWAY";
export const PAYMENT_GATEWAY_ERR = "PAYMENT_GATEWAY_ERR";
export const PAYMENT_GATEWAY_LOADING = "PAYMENT_GATEWAY_LOADING";

//TIME SLOTS

export const ADD_TIME_SLOTS = "ADD_TIME_SLOTS";
export const DELETE_TIME_SLOTS = "DELETE_TIME_SLOTS";
export const TIME_SLOTS_ERR = "TIME_SLOTS_ERR";
export const TIME_SLOTS_LOADING = "TIME_SLOTS_LOADING";
