const React = require('react-native');
const {StyleSheet, Platform, Dimensions} = React;
export default {
  container: {
    flex: 1,
    backgroundColor: 'white',
    height: '100%',
    width: '100%',
  },
  line: {
    borderBottomColor: '#bdbdbd',
    borderBottomWidth: 0.5,
    marginTop: 10,
  },
  icon: {
    fontSize: 26,
    marginStart: 20,
    marginTop: 15,
  },
  headertext: {
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 20,
    marginTop: 12,
    marginStart: 120,
  },
  profileicon: {
    width: 60,
    marginStart: 15,
    marginTop: 15,
    height: 60,
    borderRadius: 400 / 2,
  },
  row: {
    flexDirection: 'row',
  },
  column: {
    flexDirection: 'column',
  },
  header: {
    width: 300,
    backgroundColor: '#fff',
    marginStart: 13,
    borderRadius: 40,
    elevation: 2,
    marginTop: 10,
    height: 42,
  },
  itembox: {
    height: 45,
    width: '30%',
    marginStart: 10,
    marginTop: 15,
    borderColor: '#bdbdbd',
    borderRadius: 2,
    borderWidth: 1,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  itemtext: {
    padding: 5,
    textAlign: 'center',
    alignSelf: 'center',
    fontSize: 15,
    color: 'Black',
  },
  heading: {
    marginHorizontal: 15,
    marginVertical: 10,
    fontSize: 18,
    fontWeight: 'bold',
  },
  headline: {
    fontWeight: 'bold',
    color: 'black',
    fontSize: 20,
    marginBottom: 12,
  },
  filledbutton: {
    height: 50,
    width: '95%',
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: '#B72304',
    borderRadius: 5,
    marginTop: 15,
    justifyContent: 'center',
  },
  emptybutton: {
    height: 50,
    width: '95%',
    alignSelf: 'center',
    alignItems: 'center',
    borderColor: '#B72304',
    borderRadius: 5,
    borderWidth: 1,
    justifyContent: 'center',
  },
  emptybuttontext: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 17,
    color: '#B72304',
  },
  filledbuttontext: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 17,
    color: 'white',
  },
  flatlisttitle: {
    color: 'grey',
    paddingStart: 5,

    marginTop: 7,
  },
  flatlistheading: {
    paddingStart: 5,
    fontWeight: 'bold',
    fontSize: 16,
    color: 'black',
  },
  flatlistview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 8,
    marginHorizontal: 6,
    elevation: 0.5,
    borderRadius: 0.8,
  },
  flatlistitemimage: {
    height: 110,
    width: 100,
  },
  categoryview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 25,
    marginHorizontal: 15,
  },
  totalheading: {
    paddingStart: 5,
    fontWeight: 'bold',
    fontSize: 16,
    color: '#B72304',
  },
  bluetext: {
    fontWeight: 'bold',
    fontSize: 17,
    marginTop: 5,
    alignSelf: 'center',
    color: '#2196f3',
  },
  noftificationtext: {
    paddingStart: 5,
    fontWeight: 'bold',
    fontSize: 14,
    padding: 10,
    marginRight: 20,
    color: 'black',
  },
  loginbtnview: {
    borderRadius: 40,
    height: 70,
    alignSelf: 'flex-end',
    width: 70,
    marginTop: 30,
    backgroundColor: '#B72304',
    marginRight: 40,
  },
  loginbtnicon: {
    color: 'white',
    fontSize: 30,
    alignSelf: 'center',
    paddingTop: 20,
  },
  closeicon: {
    fontSize: 26,
    paddingTop: 20,
  },
  placeholder: {
    borderRadius: 40,
    color: 'black',
    borderWidth: 1,
  },
  text: {
    color: 'grey',
    width: 250,
    paddingStart: 5,
    marginTop: 7,
  },
  keywordview: {
    flexDirection: 'row',
    paddingEnd: 35,
    paddingStart: 15,
    alignSelf: 'center',
  },
};
